Create .metadata.json
magento-research/upward-php pull request #89
Opened 2021-10-19 19:01 UTC by supernova-at

Creates the file needed for the repo metadata service.

2021-10-20 14:19 UTC, anthoula requested changes

2021-10-20 14:19 UTC, anthoula commented on .github/.metadata.json
> +        "branchesToScan": ["develop"]
Should `branchesToScan` include "master" ? Looks like `master` is more up-to-date than `develop`

2021-10-20 14:25 UTC, tjwiebell commented
Please deliver this change to magento-commerce/upward-php. I can check with Mehryar on branch syncing, as @anthoula pointed out, it looks like `develop` is not being synced properly. I think we're also going to delete the `master` branch to align more with core delivery profile, and move away from git-flow.

2021-10-21 17:07 UTC, supernova-at commented
Closed in favor of https://github.com/magento-commerce/upward-php/pull/5.

2021-10-21 17:07 UTC, closed without merging